spring:
  rabbitmq:
    username: guest
    password: guest
    addresses: 127.0.0.1:5672
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        ##消费者的最小数量
        concurrency: 5
        ## manual:手动 ack（确认）
        acknowledge-mode: manual
        ##消费者的最大数量
        max-concurrency: 10
        ##在单个请求中处理的消息个数，应该大于等于事务数量
        prefetch: 1

  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

server:
  port: 8002



